version: '2'
services:
    oori:
      image: biotope/oori
      environment:
        - SERVER_PORT = "9090"
        - ENDPOINT_URL = "http://localhost:3030/odfData"
      ports:
        - "9090:9090"

    fuseki:
      build: fuseki/
      ports:
        - "3030:3030"

    o-mi-node:
        build: o-mi-node/
        ports:
          - "8080:8080"


