version: '2'
services:
    oori:
      image: biotope/oori
      environment:
        - SERVER_PORT = "8080"
        - ENDPOINT_URL = "http://localhost:3030/odfData"
      ports:
        - "9090:9090"

    fuseki:
      build: fuseki/
      image: oori/fuseki
      ports:
        - "3030:3030"
